import Vue from 'vue'

import { Button } from 'vant';
Vue.use(Button);
import { Toast } from 'vant';
Vue.use(Toast);
import { Icon } from 'vant';
Vue.use(Icon);
import { Search } from 'vant';
Vue.use(Search);
import { Tabbar, TabbarItem } from 'vant';
Vue.use(Tabbar);
Vue.use(TabbarItem);
import { Skeleton } from 'vant';
Vue.use(Skeleton);
import { List } from 'vant';
Vue.use(List);
import { PullRefresh } from 'vant';
Vue.use(PullRefresh);
import { Tab, Tabs } from 'vant';
Vue.use(Tab);
Vue.use(Tabs);
import { Image as VanImage } from 'vant';
Vue.use(VanImage);
import { NavBar } from 'vant';
Vue.use(NavBar);
import { Sticky } from 'vant';
Vue.use(Sticky);
import { Field } from 'vant';
Vue.use(Field);
import { Popup } from 'vant';
Vue.use(Popup);